### PR TITLE
Async cluster construction

### PR DESCRIPTION
**Pull request by vertexclique**
Launch and run AP cluster in the async environment.

### CODE REVIEW

**Review by o0Ignition0o — APPROVED** [review]
Maybe we can enforce the checks in the CI as a followup PR?

**Comment by vertexclique** [comment]
> Maybe we can enforce the checks in the CI as a followup PR?

I've just enabled "don't merge if checks won't pass". Isn't it what we want?

**Comment by o0Ignition0o** [comment]
I meant the checks in checks.sh, but that’s nice to have as well!

**Comment by vertexclique** [comment]
Ok, I will do that to run config for checks too. I hate writing YAML. here we go again.

**Comment by o0Ignition0o** [comment]
Dw I can pick it up if you assign me, I’ve done Travis ci yml but no gh actions yet !

**Pull request merged**
